#!/bin/sh

echo ""
echo "flac2mp4 - script de conversão de áudio FLAC para MP4 (AAC)"
echo "Por Arlindo \"Nighto\" Pereira"
echo ""

if [ "$2" ]
then
	flac --totally-silent -d -c "$1" | faac - -o "$(pwd)/$(basename "$1" .flac).m4a" \
	--title "$(metaflac --show-tag=TITLE "$1" | sed 's/TITLE=//g')" \
	--artist "$(metaflac --show-tag=ARTIST "$1" | sed 's/ARTIST=//g')" \
	--album "$(metaflac --show-tag=ALBUM "$1" | sed 's/ALBUM=//g')" \
	--year "$(metaflac --show-tag=DATE "$1" | sed 's/DATE=//g')" \
	--track "$(metaflac --show-tag=TRACKNUMBER "$1" | sed 's/TRACKNUMBER=//g')" \
	--genre "$(metaflac --show-tag=GENRE "$1" | sed 's/GENRE=//g')" \
	--cover-art "$2"
elif [ "$1" ]
then
	flac --totally-silent -d -c "$1" | faac - -o "$(pwd)/$(basename "$1" .flac).m4a" \
	--title "$(metaflac --show-tag=TITLE "$1" | sed 's/TITLE=//g')" \
	--artist "$(metaflac --show-tag=ARTIST "$1" | sed 's/ARTIST=//g')" \
	--album "$(metaflac --show-tag=ALBUM "$1" | sed 's/ALBUM=//g')" \
	--year "$(metaflac --show-tag=DATE "$1" | sed 's/DATE=//g')" \
	--track "$(metaflac --show-tag=TRACKNUMBER "$1" | sed 's/TRACKNUMBER=//g')" \
	--genre "$(metaflac --show-tag=GENRE "$1" | sed 's/GENRE=//g')"
else
	echo "Entre com o nome do arquivo para converter:"
	echo "flac2mp4 arquivo.flac [capa-do-disco]"
	echo ""
exit 1
fi

